print("Paso 1: Verificar el clima. ¿El clima es bueno para ir a la playa?")
print("Paso 2: Preparar lo necesario para el viaje:")
print("- Empacar traje de baño")
print("- Empacar protector solar")
print("- Empacar toalla")
print("- Empacar agua y comida")
print("- Empacar gafas de sol")

print("Paso 3: Elegir el medio de transporte. Opciones: coche, bicicleta o caminando.")
print("Paso 4: Revisar el transporte según la opción elegida:")
print("- Si vas en coche, revisa el nivel de combustible.")
print("- Si vas en bicicleta, revisa la presión de las llantas.")
print("- Si vas caminando, usa zapatos cómodos.")

print("Paso 5: Emprender el viaje hacia la playa.")
print("Paso 6: Llegar a la playa y disfrutar:")
print("- Nadar en el mar")
print("- Tomar el sol")
print("- Jugar en la arena")

print("¡Fin del viaje! Esperamos que lo hayas disfrutado.")